config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show new edit create destroy update] do
    resources :reviews, only: %i[new create]
  end
  resources :animals, only: %i[new create edit update destroy] do
    resources :missions, only: %i[new create edit update destroy] do
      post '/apply', to: 'missions#apply'
    end
  end
  get '/missions', to: 'missions#index'
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :missions, dependent: :destroy
  validates :name, presence: true
  validates :species, presence: true
  validates :needs, presence: true
  validates :dangerosity, inclusion: { in: 0..5 }
  has_one_attached :photo
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mission.rb
class Mission < ApplicationRecord
  ALLOWED_STATUSES = %w[pending booked finished].freeze

  after_initialize :initialize_candidates_email, if: :new_record?

  belongs_to :animal
  belongs_to :user

  validates :city, presence: true
  validates :fee, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :animal_id, presence: true
  validates :status, presence: true, inclusion: { in: ALLOWED_STATUSES }

  def available!
    self.update!(status: 'available')
  end

  def pending!
    self.update!(status: 'pending')
  end

  def booked!
    self.update!(status: 'booked')
  end

  def finished!
    self.update!(status: 'finished')
  end

  def pending?
    self.status.eql?('pending')
  end

  def serialized_candidates
    self.candidates['candidates_email']
  end

  private

  def initialize_candidates_email
    self.candidates = {}
    self.candidates[:candidates_email] = []
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  validates :comment, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :missions
  has_many :animals
  has_many :reviews
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def show
    @animal = Animal.find(params[:id])
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    @animal.save

    redirect_to user_path(current_user)
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.user == current_user
      @animal.update(animal_params)
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    if @animal.user == current_user
      @animal.destroy
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user)
    end
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :species, :dangerosity, :needs, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || missions_path
  end

  def after_sign_up_path_for(resource)
    stored_location_for(resource) || missions_path
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  skip_before_action :authenticate_user!, only: :show

  def show
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :check_mission, only: [:update, :edit, :show]
  before_action :authenticate_user!, only: [:update, :edit, :show]

  attr_reader :candidates_email

  def index
    @missions = Mission.all.order(:created_at).select { |mission| mission.status == 'pending' }
  end

  def show
  end

  def new
    @animal = Animal.find(params[:animal_id])
    @mission = Mission.new
  end

  def create
    mission = Mission.new(extended_mission_params)
    if mission.save!
      redirect_to user_path(current_user)
    else

    end
  end

  def edit
  end

  def apply
    if current_user
      @mission = Mission.find(params[:mission_id])
      @mission.candidates['candidates_email'] << current_user.email
      @mission.save
      redirect_to missions_path
    else
      redirect_to new_user_session_path
    end
  end

  def update
    @mission.candidates['chosen_candidate'] = candidate_params
    if @mission.save!
      @mission.booked!
    end
    redirect_to user_path(current_user.id)
  end

  def destroy
  end

  def candidates_email(mission)
    mission.candidates['candidates_email']
  end

  private

  def check_mission
    @mission = Mission.find(params[:id])
  end

  def mission_params
    params.require(:mission).permit(:candidates, :fee, :city, :animal_id, :start_date, :end_date, :archived)
  end

  def extended_mission_params
    mission_params.merge({
      animal: animal,
      user: current_user,
      status: 'pending'
    })
  end

  def candidate_params
    params.require(:mission).require('candidates')
  end

  def animal
    Animal.find(params[:animal_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @review = Review.new
  end

  def create
    if @user != current_user
      @user = User.find(params[:user_id])
      @review = Review.new(review_params)
      @review.user = @user
      @review.save
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    if @user == current_user
      @review = Review.find(params[:id])
      @review.destroy
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_user, only: [:edit, :update, :show]
  before_action :authenticate_user!, only: [:show, :edit, :update]

  def show
    @animals = current_user.animals
    @missions = current_user.missions
    @review = Review.new
  end

  def edit
  end

  def update
    if @user == current_user
      @user.update(user_params)
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :phone, :introduction)
  end

  def check_user
    @user = User.find(params[:id])
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <%= simple_form_for @animal, url: animal_path, method: :patch do |f| %>
        <h2>Edit Animal</h2>
        <%= f.input :name, label: "Name:" %>
        <%= f.input :species, label: "Species:" %>
        <%= f.input :dangerosity, label: "Dangerosity:" %>
        <%= f.input :needs, label: "Needs:" %>
        <%= f.input :photo, as: :file %>
          <%= f.button :submit, value: 'Save changes', class:"btn btn-primary", "data-disable-with" => "Creating.."%>
      <% end %>
    </div>
  </div>

</div>

app/views/animals/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <%= simple_form_for @animal, url: animals_path, method: :post do |f| %>
        <h2>Create Animal</h2>
        <%= f.input :name, label: "Name:" %>
        <%= f.input :species, label: "Species:" %>
        <%= f.input :dangerosity, label: "Dangerosity:" %>
        <%= f.input :needs, label: "Needs:" %>
        <%= f.input :photo, as: :file %>
        <button type="button" class="btn btn-outline-primary">
          <%= f.button :submit, value: 'Create', "data-disable-with" => "Creating.." %>
        </button>
      <% end %>
    </div>
  </div>

</div>

app/views/homepage/show.html.erb
<div class="container-homepage" >
  <h1>Your best friend deserves the best pet-sitter</h1>
  <div class="container">
    <div class="row">
      <div class="col-12">
        <%= link_to "Sign-up", new_user_registration_path, class: 'btn btn-new-user' %>
        <%= link_to "Sign-in", user_session_path, class: 'btn btn-login' %>
      </div>
    </div>
<!--     <div class="row"><%= image_tag "cover-background.jpg"%></div> -->
<!--     <div class="row">
      <div class="col-12">
        <h2>Looking for a pet sitter for your cat during your holidays?</h2>
        <h2>You love pets and wish to help travelling pet owners? Whiskares helps you!</h2>
        <p>&nbsp;</p>
      </div>
    </div> -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whiskares</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <div class="row">
        <div class="col-12"></div>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        <div class="col-12"></div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/missions/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <h1>Edit mission</h1>
      <%= simple_form_for @mission, url: animal_mission_path, method: :patch do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <%= f.input :fee %>
        <%= f.input :city %>
        <%= f.submit "save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

</div>

app/views/missions/index.html.erb
<div class="container">
<h1>All Missions</h1>
<div class="cards">
  <% @missions.each do |mission| %>
      <div class="card">
          <% if mission.animal.photo.attached? %>
          <%= cl_image_tag mission.animal.photo.key%>
          <% end %>
        <h2><i class="far fa-calendar-alt fa-fw"></i> <%= mission.start_date %> - <%= mission.end_date %></h2>
        <div class="card-body">
          <div class="card-text">
            <ul class="fa-ul">
              <li><span class="fa-li"><i class="fas fa-paw fa-fw"></i></span> <b><%= mission.animal.name %></b>, <%= mission.animal.species %></li>
              <li><span class="fa-li"><i class="fas fa-exclamation-triangle fa-fw"></i></span> <%= mission.animal.dangerosity %></li>
              <li><span class="fa-li"><i class="fas fa-hand-holding-heart fw"></i></span> <%= mission.animal.needs %></li>
              <li><span class="fa-li"><i class="fas fa-map-marker-alt fa-fw"></i></span> <%= mission.city %></li>
              <li><span class="fa-li"><i class="fas fa-euro-sign fa-fw"></i></span> <%= mission.fee %> /day</li>
            </ul>
          </div>
        </div>
        <%= link_to 'Apply', animal_mission_apply_path(mission.animal, mission), method: :post, class: 'btn btn-primary rounded' %>
      </div>
    <% end %>
</div>

app/views/missions/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <h1>Create new mission</h1>
      <%= simple_form_for @mission, url: animal_missions_path(@animal), method: :post do |f| %>

        <%= f.input :start_date, placeholder: "01/11/2020" %>
        <%= f.input :end_date, placeholder: "01/11/2020" %>
        <%= f.input :fee %>
        <%= f.input :city %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [user, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :comment %>
  <%= f.submit class: "btn btn-primary rounded"%>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to missions_path, class: "navbar-brand" do %>
    <%= image_tag "logo-whiskares-v2.png", width:"444px" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-cont herols="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", missions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My account", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
    <!--<li class="nav-item dropdown">
          <%= image_tag "user.png", height:"40px", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li>-->
      <% else %>
<!--         <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li> -->
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-12">
      <h1>User profile settings</h1>
      <h2>Add and edit information about yourself: </h2>
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      <%= simple_form_for @user do |f| %>
        <%= f.input :name, required: false %>
        <%= f.input :phone, required: false %>
        <%= f.input :introduction, required: false %>
        <%= f.button :submit %>
      <% end %>
    </div>
  </div>
</div>

</div>

app/views/users/show.html.erb
<div class="container">
          <h1>My profile</h1>
  <div class="row">
    <div class="col-12">
      <div class="card text-center">

        <div class="card-body">
          <h5 class="card-title">Email: <%= @user.email %></h5>
          <h5 class="card-title">Name: <%= @user.name %></h5>
          <h5 class="card-title">Phone Number: <%= @user.phone %></h5>
          <h5 class="card-title">Introduction:  <%= @user.introduction %></h5>
          <% if @user == current_user %>
            <%= link_to "Edit profile", edit_user_path(@user), class: 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <% if @user == current_user %>
  <p></p>
  <br>
<hr>
<br>
  <h1>My animals
    <% if @user == current_user %>
    <%= link_to new_animal_path, class: 'btn add-animal', title:'Add new animal' do %>
      <i class="fas fa-plus-circle"></i>
    <% end %>
  <% end %></h1>
          <div class="cards">
            <% @animals.each do |animal| %>
              <div class="card">
                <% if animal.photo.attached? %>
                  <%= cl_image_tag animal.photo.key%>
                  <% end %>
                <h2><%= animal.name %></h2>
                <div class="card-body">
                  <ul class="fa-ul">
                  <li><span class="fa-li"><i class="fas fa-paw fa-fw"></i></span><%= animal.species %></li>
                  <li><span class="fa-li"><i class="fas fa-exclamation-triangle fa-fw"></i></span> <%= animal.dangerosity %></li>
                  <li><span class="fa-li"><i class="fas fa-hand-holding-heart fw"></i></span> <%= animal.needs %></li>
                </ul>
                </div>
                <div class="d-flex justify-content-between">
                  <%= link_to edit_animal_path(animal), :class=> "btn btn-primary rounded", :id=>"edit", title:"Edit animal" do %>
                  <i class="fas fa-edit"></i>
                  <% end %>
                  <%= link_to animal_path(animal),
                  method: :delete,
                  data: { confirm: "Are you sure?" },
                  class: 'btn btn-primary rounded', title:"Delete animal", :id=>"delete" do %>
                  <i class="fas fa-trash-alt"></i>
                  <% end %>
                  <%= link_to new_animal_mission_path(animal), class: 'btn btn-primary rounded', title:"Add new mission" do %>
                  <i class="fas fa-calendar-plus"></i>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
  <% end %>
  <% if @user == current_user %>
  <p></p>
<br>
<hr>
<br>

  <h1>Your pending missions</h1>

            <div class="cards">
              <% @missions.each do |mission| %>
                <div class="card">
                  <h2 style="background-color: #f9b233;"><i class="far fa-calendar-alt fa-fw"></i> <%= mission.start_date %> - <%= mission.end_date %></h2>
                  <div class="card-body">
                    <div class="card-text">
                      <ul class="fa-ul">
                        <li><span class="fa-li"><i class="fas fa-tag fa-fw"></i></span> <%= mission.status %></li>
                        <li><span class="fa-li"><i class="fas fa-paw fa-fw"></i></span> <b><%= mission.animal.name %></b>, <%= mission.animal.species %></li>
                        <li><span class="fa-li"><i class="fas fa-map-marker-alt fa-fw"></i></span> <%= mission.city %></li>
                      </ul>
                      <% if mission.pending? %>
                      <p><b>Select a candidate</b></p>
                        <%= simple_form_for mission, url: animal_mission_path(mission.animal, mission), method: :patch do |f| %>
                          <%= f.input :candidates, collection: mission.serialized_candidates %>
                          <%= f.submit "Select candidate", class: "btn btn-primary" %>
                        <% end %>
                        <p></p>
                        <p><b>Candidates </b></p>
                        <% mission.serialized_candidates.each do |candidate|  %>
                        <% user = User.find_by_email(candidate) %>
                        <%= link_to candidate, user_path(user) %>
                      <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
  <% end %>
<p></p>
<br>
<hr>
<br>
<h1>Reviews</h1>
    <div class="row">
      <div class="col-12">

        <% if @user.reviews.empty? %>
          <h3>Be the first to add a review to this user!</h3>
        <% else %>
            <% @user.reviews.each do |r| %>
              <h4><%= r.comment %> - <%= r.rating %></h4>
            <% end %>
        <% end %>
        <% if @user == current_user %>
          <p>Cannot review own page</p>
        <% else %>
          <%= render "reviews/new", user: @user, review: @review %>
        <% end %>
      </div>
    </div>

</div>